-- MySQL Script generated by MySQL Workbench
-- Wed May  7 21:45:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stat` DEFAULT CHARACTER SET utf8 ;
USE `stat` ;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(320) NULL,
  `name` VARCHAR(45) NULL,
  `pass` VARCHAR(100) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `images` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `img` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `football_leagues_season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_leagues_season` (
  `idleagues` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `count` INT NOT NULL,
  `img` INT NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`idleagues`),
  INDEX `id_user_idx` (`id_user` ASC) ,
  INDEX `league_img_idx` (`img` ASC) ,
  CONSTRAINT `id_user_f_unknown`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `league_img_f_unknown`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `football_teams_season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_teams_season` (
  `idteams` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `homeCount` INT NOT NULL,
  `awayCount` INT NOT NULL,
  `img` INT NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`idteams`),
  INDEX `id_user_idx` (`id_user` ASC) ,
  INDEX `team_img_idx` (`img` ASC) ,
  CONSTRAINT `id_user_unknown`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `team_img_unknown`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `football_broker_season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_broker_season` (
  `league_id` INT NOT NULL,
  `teams_id` INT NOT NULL,
  PRIMARY KEY (`league_id`, `teams_id`),
  INDEX `team_idx` (`teams_id` ASC) ,
  CONSTRAINT `league_unknown`
    FOREIGN KEY (`league_id`)
    REFERENCES `football_leagues_season` (`idleagues`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `team_unknown`
    FOREIGN KEY (`teams_id`)
    REFERENCES `football_teams_season` (`idteams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basketball_leagues_season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basketball_leagues_season` (
  `id` INT NOT NULL,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`id_user` ASC) ,
  INDEX `kleague_img_idx` (`img` ASC) ,
  CONSTRAINT `user_unknown`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `kleague_img_unknown`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basketball_teams_season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basketball_teams_season` (
  `id` INT NOT NULL,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `home_count` INT NULL,
  `away_count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`id_user` ASC) ,
  INDEX `kteams_img_idx` (`img` ASC) ,
  CONSTRAINT `user_unknown_2`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `kteams_img_unknown`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basketball_broker_season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basketball_broker_season` (
  `id_league` INT NOT NULL,
  `id_teams` INT NOT NULL,
  PRIMARY KEY (`id_league`, `id_teams`),
  INDEX `teams_idx` (`id_teams` ASC) ,
  CONSTRAINT `league_unknown_2`
    FOREIGN KEY (`id_league`)
    REFERENCES `basketball_leagues_season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `teams_unknown`
    FOREIGN KEY (`id_teams`)
    REFERENCES `basketball_teams_season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `football_leagues_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_leagues_year` (
  `idleagues` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `count` INT NOT NULL,
  `img` INT NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`idleagues`),
  INDEX `id_user_idx` (`id_user` ASC) ,
  INDEX `league_img_idx` (`img` ASC) ,
  CONSTRAINT `id_user0_unknown`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `league_img0_unknown`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `football_teams_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_teams_year` (
  `idteams` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `homeCount` INT NOT NULL,
  `awayCount` INT NOT NULL,
  `img` INT NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`idteams`),
  INDEX `id_user_idx` (`id_user` ASC) ,
  INDEX `team_img_idx` (`img` ASC) ,
  CONSTRAINT `id_user1_unknown`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `team_img0_unknown`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `football_broker_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_broker_year` (
  `league_id` INT NOT NULL,
  `teams_id` INT NOT NULL,
  PRIMARY KEY (`league_id`, `teams_id`),
  INDEX `team_idx` (`teams_id` ASC) ,
  CONSTRAINT `league0_unknown`
    FOREIGN KEY (`league_id`)
    REFERENCES `football_leagues_year` (`idleagues`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `team0_unknown`
    FOREIGN KEY (`teams_id`)
    REFERENCES `football_teams_year` (`idteams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basketball_leagues_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basketball_leagues_year` (
  `id` INT NOT NULL,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`id_user` ASC) ,
  INDEX `kleague_img_idx` (`img` ASC) ,
  CONSTRAINT `user0_unknown`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `kleague_img0_unknown`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basketball_teams_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basketball_teams_year` (
  `id` INT NOT NULL,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `home_count` INT NULL,
  `away_count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`id_user` ASC) ,
  INDEX `kteams_img_idx` (`img` ASC) ,
  CONSTRAINT `user1_unknown`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `kteams_img0_unknown`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basketball_broker_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basketball_broker_year` (
  `id_league` INT NOT NULL,
  `id_teams` INT NOT NULL,
  PRIMARY KEY (`id_league`, `id_teams`),
  INDEX `teams_idx` (`id_teams` ASC) ,
  CONSTRAINT `league1_unknown`
    FOREIGN KEY (`id_league`)
    REFERENCES `basketball_leagues_year` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `teams0_unknown`
    FOREIGN KEY (`id_teams`)
    REFERENCES `basketball_teams_year` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs_leagues_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs_leagues_year` (
  `id` INT NOT NULL,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`id_user` ASC) ,
  INDEX `kleague_img_idx` (`img` ASC) ,
  CONSTRAINT `user00_unknown`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `kleague_img00_unknown`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs_teams_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs_teams_year` (
  `id` INT NOT NULL,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `home_count` INT NULL,
  `away_count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`id_user` ASC) ,
  INDEX `kteams_img_idx` (`img` ASC) ,
  CONSTRAINT `user10_unknown`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `kteams_img00_unknown`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs_broker_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs_broker_year` (
  `id_league` INT NOT NULL,
  `id_teams` INT NOT NULL,
  PRIMARY KEY (`id_league`, `id_teams`),
  INDEX `teams_idx` (`id_teams` ASC) ,
  CONSTRAINT `league10_unknown`
    FOREIGN KEY (`id_league`)
    REFERENCES `cs_leagues_year` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `teams00_unknown`
    FOREIGN KEY (`id_teams`)
    REFERENCES `cs_teams_year` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lol_leagues_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_leagues_year` (
  `id` INT NOT NULL,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`id_user` ASC) ,
  INDEX `kleague_img_idx` (`img` ASC) ,
  CONSTRAINT `user01_unknown`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `kleague_img01_unknown`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lol_teams_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_teams_year` (
  `id` INT NOT NULL,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `home_count` INT NULL,
  `away_count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`id_user` ASC) ,
  INDEX `kteams_img_idx` (`img` ASC) ,
  CONSTRAINT `user11_unknown`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `kteams_img01_unknown`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loll_broker_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_broker_year` (
  `id_league` INT NOT NULL,
  `id_teams` INT NOT NULL,
  PRIMARY KEY (`id_league`, `id_teams`),
  INDEX `teams_idx` (`id_teams` ASC) ,
  CONSTRAINT `league11_unknown`
    FOREIGN KEY (`id_league`)
    REFERENCES `lol_leagues_year` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `teams01_unknown`
    FOREIGN KEY (`id_teams`)
    REFERENCES `lol_teams_year` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
