-- MySQL Script generated by MySQL Workbench
-- Mon Jun  2 22:07:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id_users` INT NULL AUTO_INCREMENT,
  `mail` VARCHAR(320) NULL,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `images` (
  `id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `img` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `football_leagues_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_leagues_year` (
  `id` INT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_fyl_user_idx` (`id_user` ASC) ,
  INDEX `FK_fyl_img_idx` (`img` ASC) ,
  CONSTRAINT `FK_fyl_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_fyl_img`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `football_leagues_season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_leagues_season` (
  `id` INT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_fsl_user_idx` (`id_user` ASC) ,
  INDEX `FK_fsl_img_idx` (`img` ASC) ,
  CONSTRAINT `FK_fsl_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_fsl_img`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `football_teams_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_teams_year` (
  `id` INT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `home_count` INT NULL,
  `away_count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_fyt_user_idx` (`id_user` ASC) ,
  INDEX `FK_fyt_img_idx` (`img` ASC) ,
  CONSTRAINT `FK_fyt_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_fyt_img`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `football_teams_season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_teams_season` (
  `id` INT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `home_count` INT NULL,
  `away_count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_fst_user_idx` (`id_user` ASC) ,
  INDEX `FK_fst_img_idx` (`img` ASC) ,
  CONSTRAINT `FK_fst_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_fst_img`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `football_broker_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_broker_year` (
  `id_league` INT NULL,
  `id_team` INT NULL,
  PRIMARY KEY (`id_league`, `id_team`),
  INDEX `FK_fyear_team_idx` (`id_team` ASC) ,
  CONSTRAINT `FK_fyear_league`
    FOREIGN KEY (`id_league`)
    REFERENCES `football_leagues_year` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_fyear_team`
    FOREIGN KEY (`id_team`)
    REFERENCES `football_teams_year` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footabll_broker_season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_broker_season` (
  `id_league` INT NULL,
  `id_team` INT NULL,
  PRIMARY KEY (`id_league`, `id_team`),
  INDEX `FK_fseason_team_idx` (`id_team` ASC) ,
  CONSTRAINT `FK_fseason_league`
    FOREIGN KEY (`id_league`)
    REFERENCES `football_leagues_season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_fseason_team`
    FOREIGN KEY (`id_team`)
    REFERENCES `football_teams_season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basketball_leagues_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basketball_leagues_year` (
  `id` INT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_byl_user_idx` (`id_user` ASC) ,
  INDEX `FK_byl_img_idx` (`img` ASC) ,
  CONSTRAINT `FK_byl_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_byl_img`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basketball_leagues_season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basketball_leagues_season` (
  `id` INT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_bsl_user_idx` (`id_user` ASC) ,
  INDEX `FK_bsl_img_idx` (`img` ASC) ,
  CONSTRAINT `FK_bsl_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_bsl_img`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basketball_teams_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basketball_teams_year` (
  `id` INT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `home_count` INT NULL,
  `away_count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_byt_user_idx` (`id_user` ASC) ,
  INDEX `FK_byt_img_idx` (`img` ASC) ,
  CONSTRAINT `FK_byt_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_byt_img`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basketball_teams_season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basketball_teams_season` (
  `id` INT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `home_count` INT NULL,
  `away_count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_bst_user_idx` (`id_user` ASC) ,
  INDEX `FK_bst_img_idx` (`img` ASC) ,
  CONSTRAINT `FK_bst_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_bst_img`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basketball_broker_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basketball_broker_year` (
  `id_league` INT NULL,
  `id_team` INT NULL,
  PRIMARY KEY (`id_league`, `id_team`),
  INDEX `FK_byear_team_idx` (`id_team` ASC) ,
  CONSTRAINT `FK_byear_league`
    FOREIGN KEY (`id_league`)
    REFERENCES `basketball_leagues_year` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_byear_team`
    FOREIGN KEY (`id_team`)
    REFERENCES `basketball_teams_year` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basketball_broker_season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basketball_broker_season` (
  `id_league` INT NULL,
  `id_team` INT NULL,
  PRIMARY KEY (`id_league`, `id_team`),
  INDEX `FK_bseason_team_idx` (`id_team` ASC) ,
  CONSTRAINT `FK_bseason_league`
    FOREIGN KEY (`id_league`)
    REFERENCES `basketball_leagues_season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_bseason_team`
    FOREIGN KEY (`id_team`)
    REFERENCES `basketball_teams_season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lol_leagues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_leagues` (
  `id` INT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_lol_user_idx` (`id_user` ASC) ,
  INDEX `FK_lol_img_idx` (`img` ASC) ,
  CONSTRAINT `FK_loll_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_loll_img`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lol_teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_teams` (
  `id` INT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `home_count` INT NULL,
  `away_count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_lolt_user_idx` (`id_user` ASC) ,
  INDEX `FK_lolt_img_idx` (`img` ASC) ,
  CONSTRAINT `FK_lolt_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_lolt_img`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lol_broker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_broker` (
  `id_league` INT NULL,
  `id_team` INT NULL,
  PRIMARY KEY (`id_league`, `id_team`),
  INDEX `FK_lol_team_idx` (`id_team` ASC) ,
  CONSTRAINT `FK_lol_league`
    FOREIGN KEY (`id_league`)
    REFERENCES `lol_leagues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_lol_team`
    FOREIGN KEY (`id_team`)
    REFERENCES `lol_teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs_leagues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs_leagues` (
  `id` INT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_csl_user_idx` (`id_user` ASC) ,
  INDEX `FK_csl_img_idx` (`img` ASC) ,
  CONSTRAINT `FK_csl_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_csl_img`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs_teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs_teams` (
  `id` INT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `name` VARCHAR(45) NULL,
  `home_count` INT NULL,
  `away_count` INT NULL,
  `img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_cst_user_idx` (`id_user` ASC) ,
  INDEX `FK_cst_img_idx` (`img` ASC) ,
  CONSTRAINT `FK_cst_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_cst_img`
    FOREIGN KEY (`img`)
    REFERENCES `images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs_broker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs_broker` (
  `id_league` INT NULL,
  `id_team` INT NULL,
  PRIMARY KEY (`id_league`, `id_team`),
  INDEX `FK_cs_team_idx` (`id_team` ASC) ,
  CONSTRAINT `FK_cs_league`
    FOREIGN KEY (`id_league`)
    REFERENCES `cs_leagues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_cs_team`
    FOREIGN KEY (`id_team`)
    REFERENCES `cs_teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
